### ISSUE TITLE
build camp checklist

### ISSUE THREAD

**Issue by hexfusion** [sbatschelet/SpaceCamp#19]
**phase one**
- [x] create dir structure for overlay
- [x] build mount and nspawn units
- [ ] populate /etc/machine-id
- [ ] chroot? into system and create users core, $campuser
- [ ] install user keys
- [ ] enable fleet/etcd
- [x] launch

**phase two**
- [ ] register skydns

**Comment by hexfusion** [comment]
racke1: inet 192.168.5.68  netmask 255.255.255.0  broadcast 192.168.5.255
[07:06am] racke1: gw 192.168.5.254
